# Generated by Django 3.2 on 2021-04-24 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='post',
            name='important',
            field=models.ManyToManyField(blank=True, default=None, related_name='important', to=settings.AUTH_USER_MODEL),
        ),
    ]
