# Generated by Django 3.2 on 2021-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210425_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Busy Thinking of awesome bio !'),
        ),
    ]
